apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: delorenj@delo.sh
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
stringData:
  api-token: "8uS4nHflVYMGq6m6YysHWQLKRVZMk83A-Z0gQOtg"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: langflow-delo-sh
  namespace: default
spec:
  secretName: langflow-delo-sh-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - langflow.delo.sh
