services:
  marker-api:
    image: savatar101/marker-api:0.3
    container_name: marker-api
    ports:
      - "3333:8000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - marker-api-data:/app/data
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - proxy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.marker.entrypoints=websecure"
      - "traefik.http.routers.marker.rule=Host(`marker.delo.sh`) || Host(`marker.delorenzo.family`)"
      - "traefik.http.routers.marker.tls=true"
      - "traefik.http.routers.marker.tls.certresolver=letsencrypt"
      - "traefik.http.services.marker.loadbalancer.server.port=3333"


networks:
  proxy:
    external: true

volumes:
  marker-api-data: