# Global defaults
x-common: &common
  restart: unless-stopped
  networks:
    - proxy
  security_opt:
    - no-new-privileges:true
# Media service defaults (for services that use gluetun)
x-media-service: &media-service
  restart: unless-stopped
  network_mode: "service:gluetun"
  depends_on:
    - gluetun
  environment: &media-env
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TZ}
services:
  # Proxy Stack
  traefik:
    <<: *common
    extends:
      file: stacks/proxy/compose.yml
      service: traefik
  # Media Stack - VPN Gateway
  gluetun:
    <<: *common
    extends:
      file: stacks/media/compose.yml
      service: gluetun
  vpn-monitor:
    <<: *common
    extends:
      file: stacks/media/compose.yml
      service: vpn-monitor
    depends_on:
      - gluetun
  # Media Stack - VPN Clients
  qbittorrent:
    <<: *media-service
    extends:
      file: stacks/media/compose.yml
      service: qbittorrent
  prowlarr:
    <<: *media-service
    extends:
      file: stacks/media/compose.yml
      service: prowlarr
  jellyfin:
    <<: *media-service
    extends:
      file: stacks/media/compose.yml
      service: jellyfin
  flaresolverr:
    <<: *media-service
    extends:
      file: stacks/media/compose.yml
      service: flaresolverr
  # Non-VPN Services
  exportarr:
    <<: *media-service  # Changed from common to media-service
    extends:
      file: stacks/media/compose.yml
      service: exportarr
    depends_on:
      - gluetun
      - prowlarr
  # Monitoring Stack
  prometheus:
    <<: *common
    extends:
      file: stacks/utils/monitoring/compose.yml
      service: prometheus
  grafana:
    <<: *common
    extends:
      file: stacks/utils/monitoring/compose.yml
      service: grafana
    depends_on:
      - prometheus
      - loki
  loki:
    <<: *common
    extends:
      file: stacks/utils/monitoring/compose.yml
      service: loki
  promtail:
    <<: *common
    extends:
      file: stacks/utils/monitoring/compose.yml
      service: promtail
    depends_on:
      - loki
  node-exporter:
    <<: *common
    extends:
      file: stacks/utils/monitoring/compose.yml
      service: node-exporter
  cadvisor:
    <<: *common
    extends:
      file: stacks/utils/monitoring/compose.yml
      service: cadvisor
  # Utils Stack
  portainer:
    <<: *common
    extends:
      file: stacks/utils/compose.yml
      service: portainer
  couchdb:
    <<: *common
    extends:
      file: stacks/utils/compose.yml
      service: couchdb
  scripts:
    <<: *common
    extends:
      file: stacks/utils/scripts/compose.yml
      service: scripts
  # ai Stack
  ai_db:
    <<: *common
    extends:
      file: stacks/ai/compose.yml
      service: ai_db
  weaviate:
    <<: *common
    extends:
      file: stacks/ai/compose.yml
      service: weaviate
  litellm:
    <<: *common
    extends:
      file: stacks/ai/compose.yml
      service: litellm
  bolt:
    <<: *common
    extends:
      file: stacks/ai/compose.yml
      service: bolt
networks:
  proxy:
    name: proxy
    driver: bridge
volumes:
  prometheus_data:
  grafana_data:
  loki_data:
  portainer_data:
  couchdb_data:
  weaviate_data:
