[tasks]
# Stack management
"stack:up" = """#!/bin/bash
STACK=${1:-proxy}
cd stacks/$STACK && docker compose up -d
"""

"stack:down" = """#!/bin/bash
STACK=${1:-proxy}
cd stacks/$STACK && docker compose down
"""

"stack:restart" = """#!/bin/bash
STACK=${1:-proxy}
cd stacks/$STACK && docker compose restart
"""

"stack:logs" = """#!/bin/bash
STACK=${1:-proxy}
cd stacks/$STACK && docker compose logs -f
"""

# Backup tasks
"backup:all" = "bash scripts/backup.sh"
"backup:prowlarr" = "bash scripts/backup.sh prowlarr"
"backup:qbittorrent" = "bash scripts/backup.sh qbittorrent"
"backup:traefik" = "bash scripts/backup.sh traefik"
"backup:gluetun" = "bash scripts/backup.sh gluetun"
"backup:jellyfin" = "bash scripts/backup.sh jellyfin"
"backup:radarr" = "bash scripts/backup.sh radarr"
"backup:prometheus" = "bash scripts/backup.sh prometheus"
"backup:grafana" = "bash scripts/backup.sh grafana"

# Traefik management
"traefik:show" = "cd stacks/proxy && docker compose exec traefik traefik show"
"traefik:status" = "bash scripts/traefik.sh status"
"traefik:validate" = "bash scripts/traefik.sh validate"
"traefik:add" = """#!/bin/bash
DOMAIN=$1
bash scripts/traefik.sh add $DOMAIN
"""

"traefik:remove" = """#!/bin/bash
DOMAIN=$1
bash scripts/traefik.sh remove $DOMAIN
"""

"traefik:apply" = "bash scripts/traefik.sh apply"
"traefik:logs" = "bash scripts/traefik.sh logs"
"traefik:certs" = "bash scripts/traefik.sh certs"

# System maintenance
"system:prune" = "bash scripts/prune.sh"

[env]
COMPOSE_FILE = "compose.yml"
DOCKER_DIR = "/home/delorenj/docker"
