model_list:
  - model_name: gemini-pro
    litellm_params:
      model: gemini/gemini-pro
      api_key: ${GOOGLE_API_KEY}

  - model_name: openrouter-deepseek
    litellm_params:
      model: openrouter/deepseek/deepseek-chat
      api_key: ${OPENROUTER_API_KEY}
      api_base: "https://openrouter.ai/api/v1"

router_settings:
  redis_host: http://redis
  redis_password: ${REDIS_PASSWORD}
  redis_port: 6379

general_settings:
  #  master_key: ${LITELLM_MASTER_KEY}
  #  database_url: ${DATABASE_URL}
logging:
  level: info
  log_requests: true
  log_responses: true

server_settings:
  allow_model_override: true
  max_parallel_requests: 10
  timeout: 300
