global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@delo.sh'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'discord-critical'
  routes:
  - match:
      severity: critical
    receiver: 'discord-critical'
  - match:
      severity: warning
    receiver: 'discord-warning'

receivers:
- name: 'discord-critical'
  discord_configs:
  - webhook_url: 'https://discord.com/api/webhooks/YOUR_WEBHOOK_HERE'
    title: '🚨 CRITICAL ALERT'
    message: |
      **{{ .GroupLabels.alertname }}**
      {{ range .Alerts }}
      - {{ .Annotations.summary }}
      - {{ .Annotations.description }}
      {{ end }}

- name: 'discord-warning'
  discord_configs:
  - webhook_url: 'https://discord.com/api/webhooks/YOUR_WEBHOOK_HERE'
    title: '⚠️ WARNING'
    message: |
      **{{ .GroupLabels.alertname }}**
      {{ range .Alerts }}
      - {{ .Annotations.summary }}
      {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
