services:
  go-server:
    image: gocd/gocd-server:v17.9.0
    ports:
      - "8153:8153"
      - "8154:8154"
    volumes:
      - ./godata/config/cruise-config.xml:/godata/config/cruise-config.xml
      - ${HOME}/.ssh:/root/.ssh
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gocd.entrypoints=websecure"
      - "traefik.http.routers.gocd.rule=Host(`gocd.delo.sh`)"
      - "traefik.http.routers.gocd.tls=true"
      - "traefik.http.routers.gocd.tls.certresolver=letsencrypt"
      - "traefik.http.services.gocd.loadbalancer.server.port=8153"
      - "traefik.docker.network=proxy"
  go-agent1:
    image: gocd/gocd-agent-ubuntu-16.04:v17.9.0
    links:
      - "go-server"
    depends_on:
      - "go-server"
    environment:
      AGENT_AUTO_REGISTER_KEY: "123456789abcdefgh987654321"
      GO_SERVER_URL: https://go-server:8154/go
  go-agent2:
    image: gocd/gocd-agent-ubuntu-16.04:v17.9.0
    links:
      - "go-server"
    depends_on:
      - "go-server"
    environment:
      AGENT_AUTO_REGISTER_KEY: "123456789abcdefgh987654321"
      GO_SERVER_URL: https://go-server:8154/go

networks:
  proxy:
    external: true
