services:
  damians-tutorial:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    container_name: damians-tutorial
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app/app
    networks:
      - proxy

networks:
  proxy:
    external: true
