services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # GRPC API
    volumes:
      - ./qdrant_data:/qdrant/storage
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qdrant-service.rule=Host(`qdrant.delo.sh`)"
      - "traefik.http.routers.qdrant-service.entrypoints=websecure"
      - "traefik.http.routers.qdrant-service.tls.certresolver=letsencrypt"
      - "traefik.http.services.qdrant.loadbalancer.server.port=6333"

volumes:
  qdrant_data:
    name: qdrant_data

networks:
  proxy:
    name: proxy
    external: true