services:
  bolt-diy:
    image: bolt-ai:production
    container_name: bolt-diy
    build:
      context: /home/delorenj/code/agentic-coders/bolt.diy
      dockerfile: Dockerfile
      target: bolt-ai-production
    networks:
      - proxy
    environment:
      - NODE_ENV=production
      - PORT=5173
      - GROQ_API_KEY=${GROQ_API_KEY}
      - HuggingFace_API_KEY=${HF_TOKEN}
      - OPENAI_API_KEY=${OPENROUTER_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPEN_ROUTER_API_KEY=${OPENROUTER_API_KEY}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GEMINI_API_KEY}
      - OLLAMA_API_BASE_URL=https://ollama.delo.sh
      - XAI_API_KEY=${XAI_API_KEY}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - TOGETHER_API_BASE_URL=https://api.together.xyz/v1
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - VITE_LOG_LEVEL=debug
      - DEFAULT_NUM_CTX=32768
      - RUNNING_IN_DOCKER=true
      - VITE_GITHUB_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
      - VITE_GITHUB_TOKEN_TYPE=classic
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    command: pnpm run dockerstart
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bolt-diy.entrypoints=websecure"
      - "traefik.http.routers.bolt-diy.rule=Host(`bolt.delo.sh`)"
      - "traefik.http.routers.bolt-diy.tls=true"
      - "traefik.http.routers.bolt-diy.tls.certresolver=letsencrypt"
      - "traefik.http.services.bolt-diy.loadbalancer.server.port=5173"

networks:
  proxy:
    name: proxy
    external: true
