x-shared: &shared
  depends_on:
    postgres:
      condition: service_healthy
    redis:
      condition: service_healthy
  image: n8nio/n8n
  restart: unless-stopped
  environment:
    - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_PORT=5432
    - DB_POSTGRESDB_DATABASE=n8n
    - DB_POSTGRESDB_USER=delorenj  # Using the main postgres user instead of tonny
    - DB_POSTGRESDB_PASSWORD=PeepeePeeeEEEEpEeeeepeepEEE12PEE
    - EXECUTIONS_MODE=queue
    - QUEUE_BULL_REDIS_HOST=redis
    - QUEUE_HEALTH_CHECK_ACTIVE=true
    - N8N_ENCRYPTION_KEY=sdkfj944tjgfdskjg49srijg4irgjskrgj4wkjtsj
    - WEBHOOK_URL=https://n8n.delo.sh
  volumes:
    - n8n_storage:/home/node/.n8n

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=delorenj
      - POSTGRES_PASSWORD=PeepeePeeeEEEEpEeeeepeepEEE12PEE
      - POSTGRES_DB=n8n
      - POSTGRES_NON_ROOT_USER=tonny
      - POSTGRES_NON_ROOT_PASSWORD=PeepeePeeeEEEEpEeeeepeepEEE12PEE
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: pg_isready -h localhost -U delorenj -d n8n
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:6-alpine
    restart: unless-stopped
    volumes:
      - redis_storage:/data
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    <<: *shared
    ports:
      - 5678:5678
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.rule=Host(`n8n.delo.sh`)"
      - "traefik.http.routers.n8n.tls=true"
      - "traefik.http.routers.n8n.tls.certresolver=letsencrypt"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "traefik.docker.network=proxy"
    networks:
      - default
      - proxy

  n8n-worker:
    <<: *shared
    command: worker
    depends_on:
      - n8n
    networks:
      - default
      - proxy

volumes:
  db_storage:
  n8n_storage:
  redis_storage:

networks:
  proxy:
    external: true
