x-shared: &shared
  image: n8nio/n8n
  restart: always
  environment:
    - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
    - N8N_RUNNERS_ENABLED=true
    - N8N_ENCRYPTION_KEY=${ENCRYPTION_KEY}
    - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=http://big-chungus
    - DB_POSTGRESDB_PORT=5432
    - DB_POSTGRESDB_DATABASE=n8n
    - DB_POSTGRESDB_USER=${POSTGRES_USER}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    - EXECUTIONS_MODE=queue
    - QUEUE_BULL_REDIS_HOST=redis
    - QUEUE_HEALTH_CHECK_ACTIVE=true

  volumes:
    - n8n_storage:/home/node/.n8n
  #    - n8n_nodes:/home/node/.n8n/custom
  networks:
    - proxy

services:
  n8n:
    <<: *shared
    ports:
      - 5678:5678
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.rule=Host(`n8n.delo.sh`)"
      - "traefik.http.routers.n8n.tls=true"
      - "traefik.http.routers.n8n.tls.certresolver=letsencrypt"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "traefik.docker.network=proxy"

  n8n-worker:
    <<: *shared
    command: worker
    depends_on:
      - n8n

volumes:
  n8n_storage:
# n8n_nodes:

networks:
  proxy:
    external: true
