#!/bin/bash
set -e

# Create non-root user and grant privileges
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $POSTGRES_NON_ROOT_USER WITH PASSWORD '$POSTGRES_NON_ROOT_PASSWORD';
  GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_NON_ROOT_USER;
  GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $POSTGRES_NON_ROOT_USER;
  GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $POSTGRES_NON_ROOT_USER;
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $POSTGRES_NON_ROOT_USER;
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO $POSTGRES_NON_ROOT_USER;
  
  -- This is critical: grant schema usage and create permissions
  GRANT USAGE ON SCHEMA public TO $POSTGRES_NON_ROOT_USER;
  GRANT CREATE ON SCHEMA public TO $POSTGRES_NON_ROOT_USER;
  
  -- Make the n8n user the owner of the public schema
  ALTER SCHEMA public OWNER TO $POSTGRES_NON_ROOT_USER;
EOSQL
