services:
  frontend:
    platform: linux/amd64
    container_name: openmemory-ui
    build:
      context: .
      dockerfile: Dockerfile
    image: mem0/openmemory-ui:latest
    ports:
      - "${OPENMEMORY_UI_PORT:-3000}:3000"
    networks:
      - proxy
    env_file:
      - .env
    environment:
      - PORT={OPENMEMORY_UI_PORT:-3000}
      - NEXT_PUBLIC_API_URL=http://${OPENMEMORY_API_HOST:-host.docker.internal}:${OPENMEMORY_API_PORT:-8765}
      - NEXT_PUBLIC_USER_ID=${OPENMEMORY_USER:-default_user}
    labels:
      - "traefik.http.routers.mem0ui.rule=Host(`mem.delo.sh`)"
      - "traefik.http.routers.mem0ui.entrypoints=websecure"
      - "traefik.http.routers.mem0ui.tls.certresolver=letsencrypt"
      - "traefik.http.services.mem0ui.loadbalancer.server.port=${OPENMEMORY_UI_PORT:-3000}"

networks:
  proxy:
    external: true
