#!/bin/bash

echo "🔧 Manual AdGuard Configuration Guide"
echo "====================================="

echo "The API calls failed because AdGuard requires authentication."
echo "Let's configure this manually through the web interface."
echo ""

echo "🌐 Step 1: Access AdGuard Web Interface"
echo "1. Open browser: https://adguard.delo.sh"
echo "2. Log in with your AdGuard credentials"
echo ""

echo "🔧 Step 2: Configure DNS Settings"
echo "1. Go to: Settings > DNS settings"
echo "2. Set 'Blocking mode' to: Custom IP"
echo "3. Set 'Custom blocking IPv4' to: 192.168.1.12"
echo "4. Set 'Custom blocking IPv6' to: ::"
echo "5. Set 'Blocked response TTL' to: 300"
echo "6. Click 'Save'"
echo ""

echo "📋 Step 3: Add DNS Rewrites for Testing"
echo "1. Go to: Filters > DNS rewrites"
echo "2. Click 'Add DNS rewrite'"
echo "3. Add these rules:"
echo "   Domain: roblox.com          → Answer: 192.168.1.12"
echo "   Domain: *.roblox.com        → Answer: 192.168.1.12"
echo "   Domain: facebook.com        → Answer: 192.168.1.12"
echo "   Domain: *.facebook.com      → Answer: 192.168.1.12"
echo "4. Click 'Save' for each rule"
echo ""

echo "🛡️ Step 4: Add Block Lists (Optional)"
echo "1. Go to: Filters > DNS blocklists"
echo "2. Enable existing lists or add custom ones"
echo "3. For Roblox specifically, you might need custom rules"
echo ""

echo "📱 Step 5: Configure Your Devices"
echo ""
echo "For your PHONE (Local Network):"
echo "1. WiFi Settings > Advanced/DNS"
echo "2. Set DNS to: 192.168.1.12"
echo "3. Save and reconnect to WiFi"
echo ""

echo "For your iPAD (Tailscale):"
echo "1. Tailscale Admin Panel (https://login.tailscale.com/admin/dns)"
echo "2. Add nameserver: 192.168.1.12"
echo "3. OR in iPad: Tailscale app > DNS settings > Use: 192.168.1.12"
echo ""

echo "📡 Step 6: Check Your Router (DHCP)"
echo "Many devices get DNS automatically from router."
echo "1. Router admin panel (usually 192.168.1.1)"
echo "2. DHCP/LAN settings"
echo "3. Set Primary DNS to: 192.168.1.12"
echo "4. This makes ALL devices use AdGuard automatically"
echo ""

echo "🧪 Step 7: Test Configuration"
echo "Run these commands on each device:"
echo ""
echo "# Test 1: Check if using AdGuard DNS"
echo "nslookup roblox.com"
echo "# Expected: 192.168.1.12 (if using AdGuard)"
echo "# Actual: Real Roblox IP (if bypassing AdGuard)"
echo ""
echo "# Test 2: Test redirect service directly"
echo "curl http://192.168.1.12:8888/"
echo "# Expected: HTML countdown page"
echo ""
echo "# Test 3: Test complete flow (if DNS working)"
echo "curl -v http://roblox.com/"
echo "# Expected: HTML redirect page"
echo ""

echo "🔍 Troubleshooting"
echo "=================="
echo ""
echo "If phone still times out:"
echo "• Phone is not using 192.168.1.12 as DNS"
echo "• Check WiFi DNS settings manually"
echo "• Try forgetting and reconnecting to WiFi"
echo "• Check if router DHCP is configured correctly"
echo ""
echo "If iPad on Tailscale bypasses filtering:"
echo "• Tailscale overrides local DNS settings"
echo "• Configure Tailscale to use 192.168.1.12 as DNS"
echo "• Or disable Tailscale DNS and set manually"
echo ""
echo "If devices use correct DNS but still no filtering:"
echo "• Check AdGuard Filters > DNS rewrites are saved"
echo "• Restart AdGuard: docker compose restart adguard"
echo "• Check AdGuard query logs for blocked requests"
echo ""

echo "✅ Success Indicators:"
echo "• nslookup roblox.com returns 192.168.1.12"
echo "• Browser shows countdown page when visiting roblox.com"
echo "• Automatic redirect to https://nope.delo.sh?sound=true"
echo ""
echo "Need help? Run: ./debug-redirect.sh for detailed diagnostics"