services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik-data/traefik.yml:/traefik.yml:ro
      - ./traefik-data/acme.json:/acme.json
      - ./traefik-data/dynamic:/dynamic:ro
      - ./traefik-data/scripts:/scripts:ro
    entrypoint: ["/scripts/entrypoint.sh", "/entrypoint.sh"]
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    name: proxy
    driver: bridge
volumes:
  prometheus_data:
  grafana_data:
  loki_data:
  portainer_data:
  couchdb_data:
  weaviate_data:
