services:
  web:
    image: ghcr.io/maybe-finance/maybe:latest
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://maybe:password@postgres:5432/maybe_production
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=maybe
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=maybe_production
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
