version: '3'

services:
  couchdb:
    image: couchdb:latest
    container_name: couchdb
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - ./data:/opt/couchdb/data
    ports:
      - "5984:5984"
    restart: unless-stopped