services:
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # GRPC API
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    networks:
      - proxy
    # Temporarily disable API key for testing
    # environment:
    #   - QDRANT__SERVICE__API_KEY=touchmyflappyfoldyholds

volumes:
  qdrant_data:
    external: true
    name: qdrant_data

networks:
  proxy:
    name: proxy
    external: true
