version: '3'

services:
  ffmpeg-mcp-server:
    build: .
    container_name: ffmpeg-mcp-server
    ports:
      - "8765:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}:/config
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    external: true
