services:
  scripts:
    container_name: scripts
    image: nginx:alpine
    volumes:
      - ./scripts:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "80"
    restart: unless-stopped
    networks:
      proxy:
        aliases:
          - scripts.delo.sh
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.scripts.rule=Host(`scripts.delo.sh`)"
      - "traefik.http.routers.scripts.entrypoints=web"
      - "traefik.http.services.scripts.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
