version: '3'

services:
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/New_York
    volumes:
      - ./config:/config
    network_mode: "service:gluetun"
    restart: unless-stopped