services:
  letta:
    image: letta/letta:latest
    container_name: letta
    ports:
      - "8283:8283"
    expose:
      - "8283"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.letta.rule=Host(`letta.delo.sh`)"
      - "traefik.http.routers.letta.entrypoints=websecure"
      - "traefik.http.routers.letta.tls.certresolver=letsencrypt"
      - "traefik.http.services.letta.loadbalancer.server.port=8283"
      - "traefik.docker.network=proxy"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_BASE="https://openrouter.ai/api/v1"
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - DATABASE_URL=${POSTGRES_URL}/letta
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DELONET_API_KEY=${DELONET_API_KEY}
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    name: proxy
    external: true
