version: '3.8'

services:
  exportarr-prowlarr:
    image: ghcr.io/onedr0p/exportarr:v1.1.0
    container_name: exportarr-prowlarr
    environment:
      - TZ=America/New_York
      - PORT=9707
      - URL=http://prowlarr:9696
      - APIKEY=${PROWLARR_API_KEY} # Make sure to add this to your .env file
      - ENABLE_ADDITIONAL_METRICS=true
      - ENABLE_UNKNOWN_QUEUE_ITEMS=true
    networks:
      - proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    external: true