version: '3'

services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/New_York
    volumes:
      - ./config:/config
      - ../qbittorrent/downloads:/downloads
      - /path/to/movies:/movies
    network_mode: "service:gluetun"
    restart: unless-stopped