api:
  dashboard: true
  debug: true
  insecure: true

entryPoints:
  web:
    address: ":80"

log:
  level: DEBUG
  filePath: "/dev/stdout"

accessLog:
  filePath: "/dev/stdout"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true
    network: proxy
    watch: true
