api:
  dashboard: true
  debug: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

certificatesResolvers:
  letsencrypt:
    acme:
      email: "delorenj@gmail.com"
      storage: "acme.json"
      httpChallenge:
        entryPoint: web

log:
  level: DEBUG
  filePath: "/dev/stdout"

accessLog:
  filePath: "/dev/stdout"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true
    network: proxy
    watch: true
