version: '3'
services:
  mem0:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - VECTOR_STORE_PROVIDER=qdrant
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION_NAME=mem0
      - GRAPH_STORE_PROVIDER=neo4j
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=mem0graph
    volumes:
      - ./history:/app/history
    networks:
      - proxy
    depends_on:
      neo4j:
        condition: service_healthy
  
  neo4j:
    image: neo4j:5.26.4
    networks:
      - proxy  
    healthcheck:
      test: wget http://localhost:7687 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/mem0graph
      - NEO4J_PLUGINS=["apoc"] 
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true

volumes:
  neo4j_data:

networks:
  proxy:
    external: true
