version: '3'

services:
  mem0_store:
    image: qdrant/qdrant
    volumes:
      - mem0_storage:/mem0/storage
    networks:
      - proxy
    restart: unless-stopped

  openmemory-mcp:
    image: mem0/openmemory-mcp:latest
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - USER=${USER_ID:-default_user}
      - QDRANT_HOST=mem0_store
      - QDRANT_PORT=6333
    depends_on:
      - mem0_store
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openmemory-api.entrypoints=websecure"
      - "traefik.http.routers.openmemory-api.rule=Host(`memory-api.delo.sh`)"
      - "traefik.http.routers.openmemory-api.tls=true"
      - "traefik.http.routers.openmemory-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.openmemory-api.loadbalancer.server.port=8765"

  openmemory-ui:
    image: mem0/openmemory-ui:latest
    environment:
      - NEXT_PUBLIC_API_URL=https://memory-api.delo.sh
      - NEXT_PUBLIC_USER_ID=${USER_ID:-default_user}
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openmemory-ui.entrypoints=websecure"
      - "traefik.http.routers.openmemory-ui.rule=Host(`memory.delo.sh`)"
      - "traefik.http.routers.openmemory-ui.tls=true"
      - "traefik.http.routers.openmemory-ui.tls.certresolver=letsencrypt"
      - "traefik.http.services.openmemory-ui.loadbalancer.server.port=3000"

volumes:
  mem0_storage:

networks:
  proxy:
    external: true
