name: firecrawl
services:
  playwright-service:
    build: apps/playwright-service
    environment:
      - PORT=3000
      - PROXY_SERVER=${PROXY_SERVER}
      - PROXY_USERNAME=${PROXY_USERNAME}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
      - BLOCK_MEDIA=${BLOCK_MEDIA}
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.playwright.rule=Host(`playwright.delo.sh`)"
      - "traefik.http.routers.playwright.entrypoints=websecure"
      - "traefik.http.routers.playwright.tls.certresolver=letsencrypt"
      - "traefik.http.services.playwright.loadbalancer.server.port=3002"
  
  api:
    build: apps/api
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_SNS_TOPIC=${AWS_SNS_TOPIC}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - PLAYWRIGHT_MICROSERVICE_URL=${PLAYWRIGHT_MICROSERVICE_URL:-http://playwright-service:3000}
      - USE_DB_AUTHENTICATION=${USE_DB_AUTHENTICATION}
      - PORT=${PORT:-3002}
      - NUM_WORKERS_PER_QUEUE=${NUM_WORKERS_PER_QUEUE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - SERPER_API_KEY=${SERPER_API_KEY}
      - LLAMAPARSE_API_KEY=${LLAMAPARSE_API_KEY}
      - LOGTAIL_KEY=${LOGTAIL_KEY}
      - BULL_AUTH_KEY=${BULL_AUTH_KEY}
      - TEST_API_KEY=${TEST_API_KEY}
      - POSTHOG_API_KEY=${POSTHOG_API_KEY}
      - POSTHOG_HOST=${POSTHOG_HOST}
      - SUPABASE_ANON_TOKEN=${SUPABASE_ANON_TOKEN}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_TOKEN=${SUPABASE_SERVICE_TOKEN}
      - SCRAPING_BEE_API_KEY=${SCRAPING_BEE_API_KEY}
      - HOST=${HOST:-0.0.0.0}
    depends_on:
      - redis
      - playwright-service
    ports:
      - "3002:3002"
    command: [ "pnpm", "run", "start:production" ]
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firecrawl.rule=Host(`firecrawl.delo.sh`)"
      - "traefik.http.routers.firecrawl.entrypoints=websecure"
      - "traefik.http.routers.firecrawl.tls.certresolver=letsencrypt"
      - "traefik.http.services.firecrawl.loadbalancer.server.port=3002"


  worker:
    build: apps/api
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_SNS_TOPIC=${AWS_SNS_TOPIC}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - PLAYWRIGHT_MICROSERVICE_URL=${PLAYWRIGHT_MICROSERVICE_URL:-http://playwright-service:3000}
      - USE_DB_AUTHENTICATION=${USE_DB_AUTHENTICATION}
      - PORT=${PORT:-3002}
      - NUM_WORKERS_PER_QUEUE=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - SERPER_API_KEY=${SERPER_API_KEY}
      - LLAMAPARSE_API_KEY=${LLAMAPARSE_API_KEY}
      - LOGTAIL_KEY=${LOGTAIL_KEY}
      - BULL_AUTH_KEY=${BULL_AUTH_KEY}
      - TEST_API_KEY=${TEST_API_KEY}
      - POSTHOG_API_KEY=${POSTHOG_API_KEY}
      - POSTHOG_HOST=${POSTHOG_HOST}
      - SUPABASE_ANON_TOKEN=${SUPABASE_ANON_TOKEN}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_TOKEN=${SUPABASE_SERVICE_TOKEN}
      - SCRAPING_BEE_API_KEY=${SCRAPING_BEE_API_KEY}
      - HOST=${HOST:-0.0.0.0}
    depends_on:
      - redis
      - playwright-service
      - api
    networks:
      - proxy
  redis:
    image: redis:alpine
    networks:
      - proxy
    command: redis-server --bind 0.0.0.0

networks:
  proxy:
    external: true
