http:
  middlewares:
    chorescore-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Prefix: "/"
        accessControlAllowOriginList:
          - "*"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowHeaders:
          - "Content-Type"
          - "Authorization"
          - "X-API-Key"
        accessControlMaxAge: 100

  routers:
    chorescore:
      rule: "Host(`chorescore.${DOMAIN}`)"
      entryPoints:
        - websecure
      service: chorescore
      middlewares:
        - chorescore-headers
      tls:
        certResolver: letsencrypt

  services:
    chorescore:
      loadBalancer:
        servers:
          - url: "http://chorescore-web:80"
        healthCheck:
          path: "/health"
          interval: "30s"
          timeout: "10s"
