http:
  middlewares:
    claude-notifications-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Prefix: "/"
          X-Claude-Notification: "true"
          X-Webhook-Source: "claude-notifications"
        accessControlAllowOriginList:
          - "*"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowHeaders:
          - "Content-Type"
          - "Authorization"
          - "X-API-Token"
        accessControlMaxAge: 100

    claude-notifications-ratelimit:
      rateLimit:
        burst: 100
        average: 50

  routers:
    claude-notifications:
      rule: "Host(`hook.delo.sh`)"
      entryPoints:
        - websecure
      service: claude-notifications
      middlewares:
        - claude-notifications-headers
        - claude-notifications-ratelimit
      tls:
        certResolver: letsencrypt

  services:
    claude-notifications:
      loadBalancer:
        servers:
          - url: "http://traefik-test-whoami:80"
        healthCheck:
          path: "/"
          interval: "30s"
          timeout: "10s"
          headers:
            Host: "hook.delo.sh"
