http:
  middlewares:
    auth:
      basicAuth:
        users:
          - "admin:$apr1$BCP7HW2y$oNmgVEqW27wpXkT1Shm8o0"

  routers:
    traefik-dashboard:
      rule: "Host(`traefik.delo.sh`)"
      service: api@internal
      entryPoints:
        - websecure
      middlewares:
        - auth
      tls:
        certResolver: letsencrypt

    ai-service:
      rule: "Host(`ai.delo.sh`)"
      service: lmstudio
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    qdrant-service:
      rule: "Host(`qdrant.delo.sh`)"
      service: qdrant
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

  services:
    qdrant:
      loadBalancer:
        servers:
          - url: "http://qdrant:6333"
