http:
  middlewares:
    auth:
      basicAuth:
        users:
          - "admin:$2y$05$g3/JYH3py0aTjaQ0dObvE.6H0WvI8p77jVjJMb4U0.xa1rfsAZcB6"

  routers:
    traefik-dashboard:
      rule: "Host(`traefik.delo.sh`)"
      service: api@internal
      entryPoints:
        - websecure
      middlewares:
        - auth
      tls:
        certResolver: letsencrypt

    lms-router:
      rule: "Host(`lms.delo.sh`)"
      service: lms-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    draw-router:
      rule: "Host(`draw.delo.sh`)"
      service: draw-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

  services:
    lms-service:
      loadBalancer:
        servers:
          - url: "http://localhost:1234"

    draw-service:
      loadBalancer:
        servers:
          - url: "http://localhost:3002"
