http:
  middlewares:
    home-network-only:
      ipWhiteList:
        sourceRange:
          - "192.168.0.0/16"
          - "127.0.0.1/32"
          - "::1/128"

  routers:
    # Catch-all router to proxy any port to localhost on Big-Chungus
    default-port-proxy:
      rule: "HostRegexp(`^192\\.168\\.1\\.12$`) || HostRegexp(`^big-chungus$`) || HostRegexp(`^big-chungus\\.local$`)"
      service: localhost-proxy-service
      priority: 1
      middlewares:
        - home-network-only
      entryPoints:
        - web

  services:
    localhost-proxy-service:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1"  # Forward to localhost on Big-Chungus

# For non-standard ports, we need TCP routers
tcp:
  middlewares:
    tcp-home-network-only:
      ipWhiteList:
        sourceRange:
          - "192.168.0.0/16"
          - "127.0.0.1/32"
          - "::1/128"

  routers:
    # Port 8501 specifically for your Streamlit app
    port-8501-proxy:
      rule: "HostSNI(`*`)"
      service: localhost-8501-service
      middlewares:
        - tcp-home-network-only
      entryPoints:
        - port-8501

  services:
    localhost-8501-service:
      loadBalancer:
        servers:
          - address: "127.0.0.1:8501"
