http:
  middlewares:
    flowise-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Prefix: "/"

  routers:
    flowise:
      rule: "Host(`flowise.${DOMAIN}`)"
      entryPoints:
        - websecure
      service: flowise
      middlewares:
        - flowise-headers
      tls:
        certResolver: letsencrypt

  services:
    flowise:
      loadBalancer:
        servers:
          - url: "http://flowise-flowise-1:10010"
