http:
  middlewares:
    mcp-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Prefix: "/"
        accessControlAllowOriginList:
          - "*"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowHeaders:
          - "Content-Type"
          - "Authorization"
          - "X-API-Key"
        accessControlMaxAge: 100

    mcp-auth:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"

  routers:
    mcp-admin:
      rule: "Host(`admin.mcp.delo.sh`)"
      entryPoints:
        - websecure
      service: mcp-admin
      middlewares:
        - mcp-headers
      tls:
        certResolver: letsencrypt

    mcp-api:
      rule: "Host(`mcp.delo.sh`)"
      entryPoints:
        - websecure
      service: mcp-api
      middlewares:
        - mcp-auth
        - mcp-headers
      tls:
        certResolver: letsencrypt

  services:
    mcp-admin:
      loadBalancer:
        servers:
          - url: "http://172.19.0.1:12005"

    mcp-api:
      loadBalancer:
        servers:
          - url: "http://172.19.0.1:12006"
