http:
  middlewares:
    mem0-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Prefix: "/"
        accessControlAllowOriginList:
          - "*"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowHeaders:
          - "Content-Type"
          - "Authorization"
          - "X-API-Key"
        accessControlMaxAge: 100
    mem0-strip-prefix:
      stripPrefix:
        prefixes:
          - "/mem0"

  routers:
    mem0-ui:
      rule: "Host(`mem.delo.sh`)"
      entryPoints:
        - websecure
      service: mem0-ui
      middlewares:
        - mem0-headers
        - auth@file
      tls:
        certResolver: letsencrypt

    mem0-api:
      rule: "Host(`api.mem.delo.sh`)"
      entryPoints:
        - websecure
      service: mem0-api
      middlewares:
        - mem0-headers
      tls:
        certResolver: letsencrypt

    mem0-mcp:
      rule: "Host(`mcp.delo.sh`) && PathPrefix(`/mem0`)"
      service: mem0-api
      entryPoints:
        - websecure
      middlewares:
        - mem0-headers
        - mem0-strip-prefix
      tls:
        certResolver: letsencrypt

  services:
    mem0-ui:
      loadBalancer:
        servers:
          - url: "http://openmemory-ui:3000"

    mem0-api:
      loadBalancer:
        servers:
          - url: "http://openmemory-api:8765"
