http:
  middlewares:
    n8n-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Prefix: "/"
        accessControlAllowOriginList:
          - "*"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowHeaders:
          - "Content-Type"
          - "Authorization"
          - "X-API-Key"
        accessControlMaxAge: 100

  routers:
    n8n:
      rule: "Host(`n8n.delo.sh`)"
      entryPoints:
        - websecure
      service: n8n
      middlewares:
        - n8n-headers
      tls:
        certResolver: letsencrypt

  services:
    n8n:
      loadBalancer:
        servers:
          - url: "http://192.168.1.12:5678"
        healthCheck:
          path: "/"
          interval: "30s"
          timeout: "10s"
          headers:
            Host: "n8n.delo.sh"
