http:
  middlewares:
    obot-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Prefix: "/"
        accessControlAllowOriginList:
          - "*"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
          - "PATCH"
        accessControlAllowHeaders:
          - "Content-Type"
          - "Authorization"
          - "X-API-Key"
          - "X-Requested-With"
        accessControlMaxAge: 100

  routers:
    obot:
      rule: "Host(`obot.delo.sh`)"
      entryPoints:
        - websecure
      service: obot
      middlewares:
        - obot-headers
      tls:
        certResolver: letsencrypt

  services:
    obot:
      loadBalancer:
        servers:
          - url: "http://192.168.1.12:30155"