http:
  middlewares:
    ollama-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Prefix: "/"
        accessControlAllowOriginList:
          - "*"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowHeaders:
          - "Content-Type"
          - "Authorization"
          - "X-API-Key"
        accessControlMaxAge: 100

  routers:
    ollama:
      rule: "Host(`ollama.delo.sh`) && HeadersRegexp(`X-API-Key`, `^sk-b09c0f28978b408bcd7fab6bf47279fad8c7ceda0cb08b5a$`)"
      entryPoints:
        - websecure
      service: ollama
      middlewares:
        - ollama-headers
      tls:
        certResolver: letsencrypt

  services:
    ollama:
      loadBalancer:
        servers:
          - url: "http://192.168.1.12:11434"
