http:
  middlewares:
    ollama-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Prefix: "/"

  routers:
    ollama:
      rule: "Host(`ollama.delo.sh`)"
      entryPoints:
        - websecure
      service: ollama
      middlewares:
        - ollama-headers
      tls:
        certResolver: letsencrypt

  services:
    ollama:
      loadBalancer:
        servers:
          - url: "http://192.168.1.12:11434"
