http:
  middlewares:
    opencode-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Prefix: "/"
    
    opencode-auth:
      basicAuth:
        headerField: "X-API-Key"
        users:
          # Format: "username:hashed_password"
          # Generate with: echo $(htpasswd -nB username) | sed -e s/\\$/\\$\\$/g
          - "api:$$2y$$10$$YOUR_HASHED_API_KEY_HERE"

  routers:
    opencode:
      rule: "Host(`opencode.delo.sh`)"
      entryPoints:
        - websecure
      service: opencode
      middlewares:
        - opencode-auth
        - opencode-headers
      tls:
        certResolver: letsencrypt

  services:
    opencode:
      loadBalancer:
        servers:
          - url: "http://localhost:4096"