http:
  middlewares:
    sunshine-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Prefix: "/"

  routers:
    sunshine:
      rule: "Host(`sunshine.delo.sh`)"
      entryPoints:
        - websecure
      service: sunshine
      middlewares:
        - sunshine-headers
      tls:
        certResolver: letsencrypt

  services:
    sunshine:
      loadBalancer:
        servers:
          - url: "https://localhost:47990"
