services:
  chorescore-web:
    image: nginx:alpine
    container_name: chorescore-web
    networks:
      - proxy
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chorescore.rule=Host(`chorescore.delo.sh`)"
      - "traefik.http.routers.chorescore.entrypoints=websecure"
      - "traefik.http.routers.chorescore.tls.certresolver=letsencrypt"
      - "traefik.http.services.chorescore.loadbalancer.server.port=80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  proxy:
    name: proxy
    external: true
