services:
  opencode:
    build:
      context: ../../../
      dockerfile: stacks/ai/opencode/Dockerfile
    image: opencode:latest
    container_name: opencode
    tty: true
    stdin_open: true
    environment:
      - OPENCODE_HOSTNAME=0.0.0.0
      - OPENCODE_PORT=4096
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "4096:4096"
    volumes:
      - opencode_data:/.opencode/data
      - ./config:/.opencode/config:ro
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.opencode.loadbalancer.server.port=4096"
      - "traefik.http.routers.opencode.rule=Host(`opencode.delo.sh`)"
      - "traefik.http.routers.opencode.entrypoints=websecure"
      - "traefik.http.routers.opencode.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.opencode-auth.basicauth.usersfile=/traefik-data/.htpasswd"
      - "traefik.http.routers.opencode.middlewares=opencode-auth"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4096/openapi"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  opencode_data:
    driver: local

networks:
  proxy:
    external: true
    name: proxy
