services:
  opencode:
    build:
      context: .
      dockerfile: Dockerfile
    image: opencode:latest
    container_name: opencode
    environment:
      - OPENCODE_HOSTNAME=0.0.0.0
      - OPENCODE_PORT=4096
      - GENERATE_API_KEY=${GENERATE_API_KEY:-false}
      - OPENCODE_API_KEY=${OPENCODE_API_KEY:-}
    ports:
      - "4096:4096"
    volumes:
      - opencode_data:/.opencode/data
      - ./config:/.opencode/config:ro
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.opencode.entrypoints=websecure"
      - "traefik.http.routers.opencode.rule=Host(`opencode.delo.sh`)"
      - "traefik.http.routers.opencode.middlewares=opencode-auth@file,opencode-headers@file"
      - "traefik.http.routers.opencode.service=opencode"
      - "traefik.http.routers.opencode.tls=true"
      - "traefik.http.routers.opencode.tls.certresolver=letsencrypt"
      - "traefik.http.services.opencode.loadbalancer.server.port=4096"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4096/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  opencode_data:
    driver: local

networks:
  proxy:
    external: true
    name: proxy
