#!/bin/bash

# Debug version of oc that shows raw responses

OPENCODE_URL="${OPENCODE_URL:-http://localhost:4096}"

# Create session
SESSION_ID=$(curl -s -X POST "${OPENCODE_URL}/session_create" -H "Content-Type: application/json" -d '{}' | jq -r '.id')

# Send chat
curl -s -X POST "${OPENCODE_URL}/session_chat" \
    -H "Content-Type: application/json" \
    -d "{
        \"sessionID\": \"$SESSION_ID\",
        \"providerID\": \"$1\",
        \"modelID\": \"$2\",
        \"parts\": [{
            \"type\": \"text\",
            \"text\": \"$3\"
        }]
    }" | jq .