version: '3'

services:
  squid:
    image: ubuntu/squid:latest
    container_name: proxy
    restart: unless-stopped
    ports:
      - "3128:3128"
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
      - ./passwords:/etc/squid/passwords
      - ./blocklists:/etc/squid/blocklists
    networks:
      - proxy_network

networks:
  proxy_network:
    name: proxy_network
    driver: bridge