http:
  routers:
    lmstudio:
      rule: "Host(`ai.delo.sh`)"
      service: lmstudio
      entryPoints:
        - web
        - websecure
      tls:
        certResolver: letsencrypt

  services:
    lmstudio:
      loadBalancer:
        servers:
          - url: "http://100.116.213.108:1234"