http:
  middlewares:
    auth:
      basicAuth:
        users:
          - "admin:$apr1$EZdgAuPP$jNUDwCDFILN/pVDRgqZ34/"
    
    securityHeaders:
      headers:
        stsSeconds: 31536000
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        customFrameOptionsValue: "SAMEORIGIN"