name: Deploy to Portainer

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call Portainer webhook
        run: |
          curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}

